---
- name: Gather and display facts from Cisco IOS
  hosts: cisco
  gather_facts: false
  tasks:
    - name: Gather facts
      cisco.ios.ios_facts:

    - name: Display version
      ansible.builtin.debug:
        msg: "The IOS version is: {{ ansible_net_version }}"

    - name: Display serial number
      ansible.builtin.debug:
        msg: "The serial number is: {{ ansible_net_serialnum }}"