---
- name: Publish SoT to Github repository
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Retrieve a repository from a distant location and make it available locally
      ansible.scm.git_retrieve:
        origin:
          url: https://github.com/<your Github username>/autocon2_aap_workshop
      register: repository

    - name: Copy SNMP SoT files to temporary repository
      ansible.builtin.copy:
        src: "/home/student/autocon2_aap_workshop/"
        dest: "{{ repository['path'] }}/"
        mode: "0644"

    - name: Publish the changes to Github repo
      ansible.scm.git_publish:
        path: "{{ repository['path'] }}"
        token: "{{ lookup('ansible.builtin.env', 'GH_TOKEN') }}"
