---
- name: Configure SNMP community and host on a Cisco IOS router
  hosts: cisco
  gather_facts: false
  tasks:
    - name: Configure SNMP community and host
      cisco.ios.ios_snmp_server:
        config:
          communities:
            - acl_v4: acl_uq
              name: autocon2-community
              rw: true
            - acl_v4: acl_uq
              name: ansible-community
              rw: true
          hosts:
            - host: 192.0.2.104
              traps: bgp
              version: 2c
              community_string: autocon2-community
        state: merged